name: shibooee
favicon: null
layout_spectrum: 0.3706819568760693
typography_spectrum: 0.5123381458688527
title: Shibooee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6dedb'
    - '#383e50'
    - '#0c0b11'
    - '#9aa2ad'
    - '#6e757f'
  brandStrength: 0.3956841442268342
  lightness: 0.17309432732872665
  saturation: 0.7492680959403515
  rhythmicContrast: 0.342042182572186
purpose: []
